### ISSUE TITLE
Add Vector2 IComparable and unit tests for it

### ISSUE THREAD

**Issue by Tornado-Technology** [technologists-team/hypercube#44]

**Comment by smellilac** [comment]
Здравствуйте! 

Дайте, пожалуйста, чуть больше информации о классе Vector2 IComparable и о ваших пожеланиях.

**Comment by JerryImMouse** [comment]
> Здравствуйте!
> 
> Дайте, пожалуйста, чуть больше информации о классе Vector2 IComparable и о ваших пожеланиях.

Наследуй IComparable в Vector2, добавь реализацию и тесты
